version: '3.3'
services:
  bot:
    build: .
    restart: always
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: disctfd
      MYSQL_USER: disctfd
      MYSQL_PASSWORD: disctfd